### ISSUE TITLE
relauch commands

### ISSUE THREAD

**Issue by yofukashino** [SmolAlli/smolalli.github.io#1]
well i was viewing vanilla section of your page and it includes command to automatically close dc and open vanilla for windows, same possible for mac and linux?

**Comment by yofukashino** [comment]
got  ```kill ${pid} && open ${resourcesPath.split(".app")[0]}.app  --args --vanilla``` for mac, please let me know about linux

**Comment by SmolAlli** [comment]
as if i'd help you lmao go skid elsewhere
